version: "3.8"

services:
  calculator:
    build: ./calculator
    restart: always
    ports: 
      - "3000:3000"
    networks: 
      back:
        aliases: 
          - "calculator.svc"
    depends_on: 
      - arango

  ngnix:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./ngnix/default.conf:/etc/nginx/conf.d/default.conf
      - ./product-list:/opt/app
    networks:
      back:
        aliases: 
          - "product.svc"
    depends_on:
      - product-list 
       
  product-list:
    build: ./fpm
    entrypoint: ["php-fpm"]
    working_dir: /opt/app
    ports: 
      - "9000"
    volumes: 
      - ./product-list:/opt/app
    env_file:
      - ./product-list/.env.example 
    networks: 
      back:
        aliases: 
          - "php-fpm"
    depends_on: 
      - arango

  product-list-node:
    build: ./product-list-node
    restart: always
    ports: 
     - "3333:3333"
    env_file: ./product-list-node/.env.example
    networks: 
      back:
        aliases: 
          - "product-list.node.svc"
    depends_on: 
     - arango
     - calculator

  arango:
    image: arangodb:3.7.6
    ports:
      - "8529:8529"
    volumes:
      - arango_data_vol:/var/lib/arangodb3
      - ./arango:/opt/tools
    environment:
      ARANGO_ROOT_PASSWORD: "dummy_passowrd"
      ARANGO_STORAGE_ENGINE: rocksdb 
    networks:
      back:
        aliases:
          - "arangodb.svc"

volumes:
  arango_data_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  back: