<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

namespace Api\Infrastructure\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.Discount</code>
 */
class Discount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float percentage = 1;</code>
     */
    protected $percentage = 0.0;
    /**
     * Generated from protobuf field <code>int32 value_in_cents = 2;</code>
     */
    protected $value_in_cents = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $percentage
     *     @type int $value_in_cents
     * }
     */
    public function __construct($data = NULL) {
        \Api\GPBMetadata\Calculator::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float percentage = 1;</code>
     * @return float
     */
    public function getPercentage()
    {
        return $this->percentage;
    }

    /**
     * Generated from protobuf field <code>float percentage = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setPercentage($var)
    {
        GPBUtil::checkFloat($var);
        $this->percentage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 value_in_cents = 2;</code>
     * @return int
     */
    public function getValueInCents()
    {
        return $this->value_in_cents;
    }

    /**
     * Generated from protobuf field <code>int32 value_in_cents = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setValueInCents($var)
    {
        GPBUtil::checkInt32($var);
        $this->value_in_cents = $var;

        return $this;
    }

}

